"""Generate source-backed project metadata, API/dependency reference and sitemap."""
from __future__ import annotations
import argparse
import ast
import html
import json
import re
import runpy
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def reference_data() -> dict:
    version_tree = ast.parse((ROOT / 'app/version.py').read_text())
    version = next(ast.literal_eval(n.value) for n in version_tree.body if isinstance(n, ast.Assign) and any(isinstance(t, ast.Name) and t.id == 'APP_VERSION' for t in n.targets))
    main = ast.parse((ROOT / 'app/main.py').read_text())
    routes = []
    for n in ast.walk(main):
        if not isinstance(n, ast.Call) or not isinstance(n.func, ast.Attribute) or n.func.attr != 'include_router' or not n.args:
            continue
        ref = n.args[0]
        if not isinstance(ref, ast.Attribute) or not isinstance(ref.value, ast.Name) or ref.value.id == 'ui':
            continue
        module, router = ref.value.id, ref.attr
        prefix = next((ast.literal_eval(k.value) for k in n.keywords if k.arg == 'prefix'), '')
        tree = ast.parse((ROOT / f'app/routers/{module}.py').read_text())
        for item in tree.body:
            if isinstance(item, ast.Assign) and any(isinstance(t, ast.Name) and t.id == router for t in item.targets) and isinstance(item.value, ast.Call):
                prefix += next((ast.literal_eval(k.value) for k in item.value.keywords if k.arg == 'prefix'), '')
        for func in tree.body:
            if not isinstance(func, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in func.decorator_list:
                if isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute) and isinstance(decorator.func.value, ast.Name) and decorator.func.value.id == router and decorator.func.attr in {'get','post','patch','put','delete'}:
                    routes.append({'method':decorator.func.attr.upper(), 'path':prefix + ast.literal_eval(decorator.args[0]), 'handler':f'{module}.{func.name}'})
    packages = []
    for line in (ROOT / 'requirements.txt').read_text().splitlines():
        match = re.match(r'^([A-Za-z0-9_.-]+)==([^\s;]+)', line)
        if match:
            packages.append({'name':match[1], 'version':match[2]})
    return {'version':version, 'release_status':'source release', 'release_tag':'v'+version, 'review_date':json.loads((ROOT/'release.json').read_text())['date'], 'routes':sorted(routes, key=lambda r:(r['path'], r['method'])), 'locked_runtime_packages':sorted(packages,key=lambda p:p['name'].lower()), 'browser_packages':json.loads((ROOT/'package.json').read_text())['dependencies']}


def outputs() -> dict[Path, str]:
    data = reference_data()
    rows = ''.join('<tr><td><code>'+html.escape(r['method'])+'</code></td><td><code>'+html.escape(r['path'])+'</code></td><td>'+html.escape(r['handler'])+'</td></tr>' for r in data['routes'])
    packages = ''.join('<tr><td>'+html.escape(r['name'])+'</td><td>'+html.escape(r['version'])+'</td></tr>' for r in data['locked_runtime_packages'])
    page = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Generated reference — TimeboardApp</title><link rel="stylesheet" href="../assets/css/styles.css"></head><body><header class="header"><div class="container header-inner"><a class="brand" href="/">TimeboardApp</a><nav class="nav"><a href="/docs/">Docs</a><a href="/docs/api.html">API</a><a href="/docs/chatgpt.html">ChatGPT</a></nav></div></header><main><section class="section"><div class="container"><h1>Source-generated reference</h1><p>Source version <strong>{html.escape(data['version'])}</strong>; source release <code>{html.escape(data['release_tag'])}</code>. Reviewed September 26, 2026. This describes repository source, not the deployment state of an existing instance.</p><p>Generated by <code>scripts/sync_docs.py</code> and verified in CI. <a href="../assets/project-data.json">Machine-readable metadata</a>.</p><h2>API routes</h2><table class="table"><thead><tr><th>Method</th><th>Path</th><th>Handler</th></tr></thead><tbody>{rows}</tbody></table><h2>Locked runtime dependencies</h2><table class="table"><thead><tr><th>Package</th><th>Version</th></tr></thead><tbody>{packages}</tbody></table><h2>Browser dependencies</h2><pre>{html.escape(json.dumps(data['browser_packages'],indent=2))}</pre><p>Updates require regenerating locks, vendored assets, and this reference, then passing regression/security tests.</p></div></section></main></body></html>\n'''
    page = runpy.run_path(str(ROOT/'scripts/release_metadata.py'))['decorate_html'](page)
    names = sorted({str(f.relative_to(ROOT/'docs')) for f in (ROOT/'docs').rglob('*.html') if f.name != '404.html'} | {'docs/reference.html'})
    sitemap = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ''.join('  <url><loc>https://timeboardapp.com/'+('' if n=='index.html' else n)+'</loc></url>\n' for n in names) + '</urlset>\n'
    return {ROOT/'docs/assets/project-data.json':json.dumps(data,indent=2)+'\n', ROOT/'docs/docs/reference.html':page, ROOT/'docs/sitemap.xml':sitemap}


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    mismatches = []
    for path, expected in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                mismatches.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(expected)
    if mismatches:
        raise SystemExit('Regenerate source-backed docs: '+', '.join(mismatches))
    print('Source-backed documentation is consistent')
